networks:
  galaxydb-network:
    name: galaxydb-network
    driver: bridge

services:
  galaxydb-metadata:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=galaxydb
      - POSTGRES_DB=postgres
      - PGPORT=5432
      - PGHOST=galaxydb-metadata
    networks:
      - galaxydb-network
    volumes:
      - ./loadbalancer/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3

  galaxydb-loadbalancer:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile.lb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server:/server
    image: galaxydb-lb
    ports:
      - "5000:5000"
    privileged: true
    networks:
      - galaxydb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/serverids"]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      galaxydb-metadata:
        condition: service_healthy

  galaxydb-shard-manager:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile.manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: galaxydb-shard-manager
    ports:
      - "8000:8000"
    privileged: true
    networks:
      - galaxydb-network
    depends_on:
      galaxydb-metadata:
        condition: service_healthy
      galaxydb-loadbalancer:
        condition: service_healthy
