networks:
  galaxydb-network:
    name: galaxydb-network
    driver: bridge

services:
  galaxydb-metadata:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=galaxydb
      - POSTGRES_DB=postgres
      - PGPORT=5432
      - PGHOST=galaxydb-metadata
    networks:
      - galaxydb-network
    volumes:
      - ./loadbalancer/init.sql:/docker-entrypoint-initdb.d/init.sql

  galaxydb-loadbalancer:
    build: "./loadbalancer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server:/server
    image: galaxydb-lb
    ports:
      - "5000:5000"
    privileged: true
    networks:
      - galaxydb-network
    depends_on:
      - galaxydb-metadata
